#!/usr/bin/bash

ulang="y"
while [ $ulang = "y" ]
do
clear
echo "
\033[1;37m█████████    \033[1;31m ╔═══╗╔╗─╔╗╔══╗─╔═══╗╔═══╗╔═══╗╔══╗╔══╗─╔═══╗
\033[1;37m█▄█████▄█    \033[1;31m ║╔═╗║║║─║║║╔╗║─║╔═╗║║╔═╗║║╔═╗║╚╣─╝║╔╗║─║╔══╝
\033[1;37m█\033[1;31m▼▼▼▼▼\033[1;36m_-_--_ \033[1;31m ║╚══╗║║─║║║╚╝╚╗║╚══╗║║─╚╝║╚═╝║─║║─║╚╝╚╗║╚══╗
\033[1;37m█\033[1;36m--_-_-_-_   \033[1;37m ╚══╗║║║─║║║╔═╗║╚══╗║║║─╔╗║╔╗╔╝─║║─║╔═╗║║╔══╝
\033[1;37m█\033[1;31m▲▲▲▲▲\033[1;36m-_-_-_ \033[1;37m ║╚═╝║║╚═╝║║╚═╝║║╚═╝║║╚═╝║║║║╚╗╔╣─╗║╚═╝║║╚══╗
\033[1;37m█████████    \033[1;37m ╚═══╝╚═══╝╚═══╝╚═══╝╚═══╝╚╝╚═╝╚══╝╚═══╝╚═══╝
\033[1;37m ██ ██               AUTHOR  : IVAN FIRMANSYAH

●▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬▬▬▬▬▬▬▬▬● 

\033[1;36m[\033[1;32m01\033[1;36m]\033[1;37m DARK FACEBOOK TERBARU
\033[1;36m[\033[1;32m02\033[1;36m]\033[1;37m SPAM SMS INDIHOME \033[1;32m(\033[1;33m unli\033[1;32m )
\033[1;36m[\033[1;32m03\033[1;36m]\033[1;37m TOMBOL SPESIAL
\033[1;36m[\033[1;32m04\033[1;36m]\033[1;37m SPAM SMS TRI \033[1;32m(\033[1;33m unli\033[1;32m )
\033[1;36m[\033[1;32m05\033[1;36m]\033[1;37m GARUDA DDOS
\033[1;36m[\033[1;32m06\033[1;36m]\033[1;37m SCAN IP WEBSITE
\033[1;36m[\033[1;32m07\033[1;36m]\033[1;37m PIRKIRAAN CUACA
\033[1;36m[\033[1;32m05\033[1;36m]\033[1;37m SPAM CALL
"
read -p "PILIHAN ~~> " p

if [ $p = "1" ]
then
        git clone https://github.com/BangDanz/Darksimpel
        cd Darksimpel
        python2 dark.py

elif [ $p = "2" ]
then

        sh s-indi.sh

elif [ $p = "3" ]
then

        sh tpl.sh

elif [ $p = "4" ]
then

        php 3.php

elif [ $p = "5" ]
then

        sh dos.sh

elif [ $p = "6" ]
then

        sh ip.sh

elif [ $p = "7" ]
then

        sh pkr.sh

elif [ $p = "8" ]
then

        python3 call.py

fi
done
